<?php
/**
 * WebhooksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.2
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * WebhooksApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WebhooksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteWebhook
     *
     * Delete a webhook by ID..
     *
     */
    public function testDeleteWebhook()
    {
    }

    /**
     * Test case for getWebhook
     *
     * Get a webhook by ID..
     *
     */
    public function testGetWebhook()
    {
    }

    /**
     * Test case for getWebhooks
     *
     * Fetch a list of all webhooks..
     *
     */
    public function testGetWebhooks()
    {
    }

    /**
     * Test case for patchWebhook
     *
     * Modify a webhook by ID..
     *
     */
    public function testPatchWebhook()
    {
    }

    /**
     * Test case for postWebhook
     *
     * Create a webhook..
     *
     */
    public function testPostWebhook()
    {
    }
}
