<?php
/**
 * FeatureFlagConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  LaunchDarklyApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 5.3.0
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace LaunchDarklyApi;

/**
 * FeatureFlagConfigTest Class Doc Comment
 *
 * @category    Class
 * @description FeatureFlagConfig
 * @package     LaunchDarklyApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FeatureFlagConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FeatureFlagConfig"
     */
    public function testFeatureFlagConfig()
    {
    }

    /**
     * Test attribute "on"
     */
    public function testPropertyOn()
    {
    }

    /**
     * Test attribute "archived"
     */
    public function testPropertyArchived()
    {
    }

    /**
     * Test attribute "salt"
     */
    public function testPropertySalt()
    {
    }

    /**
     * Test attribute "sel"
     */
    public function testPropertySel()
    {
    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "targets"
     */
    public function testPropertyTargets()
    {
    }

    /**
     * Test attribute "rules"
     */
    public function testPropertyRules()
    {
    }

    /**
     * Test attribute "fallthrough"
     */
    public function testPropertyFallthrough()
    {
    }

    /**
     * Test attribute "off_variation"
     */
    public function testPropertyOffVariation()
    {
    }

    /**
     * Test attribute "prerequisites"
     */
    public function testPropertyPrerequisites()
    {
    }

    /**
     * Test attribute "track_events"
     */
    public function testPropertyTrackEvents()
    {
    }

    /**
     * Test attribute "track_events_fallthrough"
     */
    public function testPropertyTrackEventsFallthrough()
    {
    }

    /**
     * Test attribute "_site"
     */
    public function testPropertySite()
    {
    }

    /**
     * Test attribute "_environment_name"
     */
    public function testPropertyEnvironmentName()
    {
    }
}
