<?php
/**
 * TokenBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  LaunchDarklyApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 5.3.0
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace LaunchDarklyApi;

/**
 * TokenBodyTest Class Doc Comment
 *
 * @category    Class
 * @description TokenBody
 * @package     LaunchDarklyApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TokenBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TokenBody"
     */
    public function testTokenBody()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "role"
     */
    public function testPropertyRole()
    {
    }

    /**
     * Test attribute "custom_role_ids"
     */
    public function testPropertyCustomRoleIds()
    {
    }

    /**
     * Test attribute "inline_role"
     */
    public function testPropertyInlineRole()
    {
    }

    /**
     * Test attribute "service_token"
     */
    public function testPropertyServiceToken()
    {
    }

    /**
     * Test attribute "default_api_version"
     */
    public function testPropertyDefaultApiVersion()
    {
    }
}
