<?php
/**
 * CustomRolesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  LaunchDarklyApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 5.3.0
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace LaunchDarklyApi;

use \LaunchDarklyApi\Configuration;
use \LaunchDarklyApi\ApiException;
use \LaunchDarklyApi\ObjectSerializer;

/**
 * CustomRolesApiTest Class Doc Comment
 *
 * @category Class
 * @package  LaunchDarklyApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomRolesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteCustomRole
     *
     * Delete a custom role by key..
     *
     */
    public function testDeleteCustomRole()
    {
    }

    /**
     * Test case for getCustomRole
     *
     * Get one custom role by key..
     *
     */
    public function testGetCustomRole()
    {
    }

    /**
     * Test case for getCustomRoles
     *
     * Return a complete list of custom roles..
     *
     */
    public function testGetCustomRoles()
    {
    }

    /**
     * Test case for patchCustomRole
     *
     * Modify a custom role by key..
     *
     */
    public function testPatchCustomRole()
    {
    }

    /**
     * Test case for postCustomRole
     *
     * Create a new custom role..
     *
     */
    public function testPostCustomRole()
    {
    }
}
