<?php
/**
 * DataExportDestinationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  LaunchDarklyApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 5.3.0
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace LaunchDarklyApi;

use \LaunchDarklyApi\Configuration;
use \LaunchDarklyApi\ApiException;
use \LaunchDarklyApi\ObjectSerializer;

/**
 * DataExportDestinationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  LaunchDarklyApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DataExportDestinationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteDestination
     *
     * Get a single data export destination by ID.
     *
     */
    public function testDeleteDestination()
    {
    }

    /**
     * Test case for getDestination
     *
     * Get a single data export destination by ID.
     *
     */
    public function testGetDestination()
    {
    }

    /**
     * Test case for getDestinations
     *
     * Returns a list of all data export destinations..
     *
     */
    public function testGetDestinations()
    {
    }

    /**
     * Test case for patchDestination
     *
     * Perform a partial update to a data export destination..
     *
     */
    public function testPatchDestination()
    {
    }

    /**
     * Test case for postDestination
     *
     * Create a new data export destination.
     *
     */
    public function testPostDestination()
    {
    }
}
