<?php
/**
 * TeamMembersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  LaunchDarklyApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 5.3.0
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace LaunchDarklyApi;

use \LaunchDarklyApi\Configuration;
use \LaunchDarklyApi\ApiException;
use \LaunchDarklyApi\ObjectSerializer;

/**
 * TeamMembersApiTest Class Doc Comment
 *
 * @category Class
 * @package  LaunchDarklyApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TeamMembersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteMember
     *
     * Delete a team member by ID..
     *
     */
    public function testDeleteMember()
    {
    }

    /**
     * Test case for getMe
     *
     * Get the current team member associated with the token.
     *
     */
    public function testGetMe()
    {
    }

    /**
     * Test case for getMember
     *
     * Get a single team member by ID..
     *
     */
    public function testGetMember()
    {
    }

    /**
     * Test case for getMembers
     *
     * Returns a list of all members in the account..
     *
     */
    public function testGetMembers()
    {
    }

    /**
     * Test case for patchMember
     *
     * Modify a team member by ID..
     *
     */
    public function testPatchMember()
    {
    }

    /**
     * Test case for postMembers
     *
     * Invite new members..
     *
     */
    public function testPostMembers()
    {
    }
}
