<?php
/**
 * UserSegmentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  LaunchDarklyApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 5.3.0
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace LaunchDarklyApi;

use \LaunchDarklyApi\Configuration;
use \LaunchDarklyApi\ApiException;
use \LaunchDarklyApi\ObjectSerializer;

/**
 * UserSegmentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  LaunchDarklyApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserSegmentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteUserSegment
     *
     * Delete a user segment..
     *
     */
    public function testDeleteUserSegment()
    {
    }

    /**
     * Test case for getExpiringUserTargetsOnSegment
     *
     * Get expiring user targets for user segment.
     *
     */
    public function testGetExpiringUserTargetsOnSegment()
    {
    }

    /**
     * Test case for getUserSegment
     *
     * Get a single user segment by key..
     *
     */
    public function testGetUserSegment()
    {
    }

    /**
     * Test case for getUserSegments
     *
     * Get a list of all user segments in the given project..
     *
     */
    public function testGetUserSegments()
    {
    }

    /**
     * Test case for patchExpiringUserTargetsOnSegment
     *
     * Update, add, or delete expiring user targets on user segment.
     *
     */
    public function testPatchExpiringUserTargetsOnSegment()
    {
    }

    /**
     * Test case for patchUserSegment
     *
     * Perform a partial update to a user segment..
     *
     */
    public function testPatchUserSegment()
    {
    }

    /**
     * Test case for postUserSegment
     *
     * Creates a new user segment..
     *
     */
    public function testPostUserSegment()
    {
    }

    /**
     * Test case for updateBigSegmentTargets
     *
     * Update targets included or excluded in a big segment.
     *
     */
    public function testUpdateBigSegmentTargets()
    {
    }
}
